### ISSUE TITLE
[ReadMe] The first 'all' should say 'of'

### ISSUE THREAD

**Issue by clairetorrez** [usmanovs/Salesforce-Interview-Handbook#17]
"The authors have studied all the existing resources online to ensure it has the best questions all all."

The first 'all' should say 'of'

**Comment by clairetorrez** [comment]
"Furthermore, this resources is getting continually updated by the other developers." 

'this' should say 'these', 
'is getting' should say 'are getting'

**Comment by usmanovs** [comment]
thank you! I fixed all 3 of the items. this is fantastic specific feedback. thank you again!!!
